package chain

import (
	"encoding/hex"
	"testing"

	"github.com/computervirtualservices/malairte/internal/crypto"
	"github.com/computervirtualservices/malairte/internal/primitives"
)

// Cross-language sighash test vectors.
//
// The constants below are the authoritative reference that the C# wallet
// implementation (CryptoService.SelfTestTaproot in mobile/ and wallet/) must
// reproduce byte-for-byte. Any drift in EITHER the Go sighash implementation
// or the C# port will fail this test here OR the SelfTestTaproot method in
// the wallet — giving us a fail-loud cross-language consistency check before
// any real taproot transaction ever hits mainnet.
//
// The fixed inputs:
//   - 32-byte private key: 0x01..0x20 (monotonically increasing, easy to
//     reproduce in any language)
//   - single P2TR input spending outpoint 0xAA..AA : 0, amount 1 000 000,
//     sequence 0xFFFFFFFF
//   - single P2PKH output to pkh 0xBB..BB, value 900 000
//   - version 2, locktime 0
//   - chain ID = mainnet magic 0x4D4C5254 ("MLRT")
//   - SIGHASH_DEFAULT (0x00)
//
// If any field above is changed, regenerate the expected hex values and
// update the matching C# hardcoded constants.
const (
	// testVecPrivKeyHex is the deterministic 32-byte secret.
	testVecPrivKeyHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"

	// testVecPrevTxIDHex is the funding tx's txid (repeated 0xAA).
	testVecPrevTxIDHex = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

	// testVecRecipientHashHex is the 20-byte pubkey hash in the output.
	testVecRecipientHashHex = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"

	testVecInputAmount int64 = 1_000_000
	testVecOutputValue int64 = 900_000
	testVecChainID     uint32 = 0x4d4c5254

	// testVecExpectedTweakedKeyHex is the 32-byte x-only taproot output key
	// derived from the fixed private key above (BIP-341 tweak with no merkle
	// root). Both the Go TapTweakPubKey and the C# port must produce this.
	testVecExpectedTweakedKeyHex = "4a95770effc923dbe8125e951a8e0f7a667ae1512eac4a933d8be96fbd591127"

	// testVecExpectedSigHashHex is the BIP-341 key-path sighash (with Malairt
	// chainID prefix) a conformant implementation MUST produce. Generated by
	// the Go code below and pinned so any future drift in either language
	// fails loud.
	testVecExpectedSigHashHex = "01a5ffdfc814dfa802d01080db2a098137a47a90535211ae03d57a878586010f"
)

// buildVectorTx constructs the canonical vector transaction.
func buildVectorTx(t *testing.T) (*primitives.Transaction, [][]byte, []int64, []byte) {
	t.Helper()
	prevTxID, err := hex.DecodeString(testVecPrevTxIDHex)
	if err != nil {
		t.Fatal(err)
	}
	recipientHash, err := hex.DecodeString(testVecRecipientHashHex)
	if err != nil {
		t.Fatal(err)
	}

	var prevID [32]byte
	copy(prevID[:], prevTxID)
	var rcpt20 [20]byte
	copy(rcpt20[:], recipientHash)

	// Version=1 matches what the C# wallet's SerializeTx writes for
	// outgoing transactions (SerializeTx hardcodes version 1 to match
	// every existing Malairt wallet build). Using version=1 here aligns
	// the Go canonical vector with what C# will actually compute.
	tx := &primitives.Transaction{
		Version: 1,
		Inputs: []primitives.TxInput{{
			PreviousOutput: primitives.OutPoint{TxID: prevID, Index: 0},
			Sequence:       0xFFFFFFFF,
		}},
		Outputs: []primitives.TxOutput{{
			Value:        testVecOutputValue,
			ScriptPubKey: primitives.P2PKHScript(rcpt20),
		}},
		LockTime: 0,
	}

	// Derive the P2TR scriptPubKey from the fixed private key.
	privBytes, err := hex.DecodeString(testVecPrivKeyHex)
	if err != nil {
		t.Fatal(err)
	}
	pubKey, err := crypto.PubKeyFromPrivKey(privBytes)
	if err != nil {
		t.Fatal(err)
	}
	xonly, err := crypto.XOnlyPubKey(pubKey)
	if err != nil {
		t.Fatal(err)
	}
	tweakedKey, _, err := crypto.TapTweakPubKey(xonly, nil)
	if err != nil {
		t.Fatal(err)
	}
	var outKey [32]byte
	copy(outKey[:], tweakedKey)
	spk := primitives.P2TRScript(outKey)

	prevScripts := [][]byte{spk}
	prevAmounts := []int64{testVecInputAmount}
	return tx, prevScripts, prevAmounts, tweakedKey
}

// TestTaprootSigHashVector computes the BIP-341 key-path sighash for the
// fixed inputs declared above and asserts it matches the pinned hex string.
//
// Procedure for regenerating the pinned value:
//  1. Set testVecExpectedSigHashHex = "".
//  2. Run this test — it prints the computed hex.
//  3. Copy that hex into testVecExpectedSigHashHex AND into
//     CryptoService.SelfTestTaproot's ExpectedSigHashHex constant on the C#
//     side.
//  4. Re-run both sides; both must pass.
func TestTaprootSigHashVector(t *testing.T) {
	tx, prevScripts, prevAmounts, tweakedKey := buildVectorTx(t)

	sigHash, err := CalcTaprootKeySpendSigHash(
		tx, 0, prevScripts, prevAmounts,
		0x00, // SIGHASH_DEFAULT
		testVecChainID,
	)
	if err != nil {
		t.Fatalf("CalcTaprootKeySpendSigHash: %v", err)
	}
	gotHex := hex.EncodeToString(sigHash[:])

	// Both derivations are checked against the pinned vectors. If either
	// the Go TapTweakPubKey or the sighash function drifts, this fails.
	gotTweakedHex := hex.EncodeToString(tweakedKey)
	if gotTweakedHex != testVecExpectedTweakedKeyHex {
		t.Errorf("tweaked output key drift: got %s, pinned %s",
			gotTweakedHex, testVecExpectedTweakedKeyHex)
	}
	if gotHex != testVecExpectedSigHashHex {
		t.Errorf("sighash drift: got %s, pinned %s", gotHex, testVecExpectedSigHashHex)
	}
}

// TestTaprootSigHashVector_SignAndVerify closes the loop: compute the sighash
// from the vector, sign it with the fixed key (tweaked per BIP-341), verify
// the signature under the tweaked output key. This protects against regressions
// in the sign/verify path that TestTaprootSigHashVector alone would not catch.
func TestTaprootSigHashVector_SignAndVerify(t *testing.T) {
	tx, prevScripts, prevAmounts, tweakedKey := buildVectorTx(t)

	sigHash, err := CalcTaprootKeySpendSigHash(
		tx, 0, prevScripts, prevAmounts,
		0x00, testVecChainID,
	)
	if err != nil {
		t.Fatal(err)
	}

	// Derive the taproot-tweaked signing scalar from the same private key.
	privBytes, err := hex.DecodeString(testVecPrivKeyHex)
	if err != nil {
		t.Fatal(err)
	}
	tweakedSec, err := crypto.TapTweakSecKey(privBytes, nil)
	if err != nil {
		t.Fatal(err)
	}
	sig, err := crypto.SchnorrSign(tweakedSec, sigHash[:])
	if err != nil {
		t.Fatal(err)
	}
	if !crypto.SchnorrVerify(tweakedKey, sigHash[:], sig) {
		t.Fatal("signature must verify under the tweaked output key")
	}
	// Tampering the sighash must make verification fail.
	tampered := sigHash
	tampered[0] ^= 1
	if crypto.SchnorrVerify(tweakedKey, tampered[:], sig) {
		t.Fatal("signature must not verify for a tampered message")
	}
}
